title: SafeTravel
url: "https://safetravel.ica.gov.sg"
favicon: /images/favicon-stp.svg
notification: 

# Site colors
colors:
  primary-color: '#C35152'
  secondary-color: '#C35152'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'

#collections
collections:
  travellers-from-australia:
    output: true
  travellers-from-brunei-darussalam:
    output: true
  travellers-from-china:
    output: true
  travellers-from-malaysia:
    output: true
  travellers-from-new-zealand:
    output: true
  travellers-from-republic-of-korea:
    output: true
  travellers-from-japan:
    output: true
  travellers-from-vietnam:
    output: true

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test
