title: SafeTravel
url: "https://safetravel.ica.gov.sg"
favicon: /images/favicon-stp.svg
notification: New entry applications under the Work Pass Holder General Lane for pass holders from higher-risk countries/regions (i.e. all countries/regions, except Australia, Brunei, Hong Kong, Macao, Mainland China, New Zealand and Taiwan) will no longer be accepted with immediate effect. Please see MOM's press release <a href="https://www.mom.gov.sg/newsroom/press-releases/2021/0705-work-pass-holders-who-have-already-obtained-approval-to-enter-to-be-rescheduled">here</a>. <br/> Affected pass holders will have their in-principle approval (IPA) validities extended. Ministry of Manpower (MOM) will share more details on this later on. In the meantime, for IPAs that are expiring soon, you can <a href="https://www.mom.gov.sg/faq/work-pass-general/how-do-i-extend-the-validity-of-an-in-principle-approval-ipa">request for an extension</a>.<br/> We seek your understanding and cooperation for such measures to enable pass holders to enter Singapore in a safe and calibrated manner, and mitigate the risk of COVID-19 importation.

# Site colors
colors:
  primary-color: '#C35152'
  secondary-color: '#C35152'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'

#collections
collections:
  air-travel-pass:
    output: true
  atp-australia:
    output: true
  atp-brunei:
    output: true
  atp-china:
    output: true
  atp-new-zealand:
    output: true
  atp-vietnam:
    output: true
  atp-taiwan:
    output: true
  rgl-brunei:
    output: true
  rgl-china:
    output: true
  rgl-japan:
    output: true
  rgl-malaysia:
    output: true
  rgl-republic-of-korea:
    output: true
  reciprocal-green-lane:
    output: true 
  periodic-commuting-arrangement:
    output: true
  returning-singapore-citizen-and-pr:
    output: true
  travel-and-health-control-measures:
    output: true
  work-pass-holder-lane:
    output: true
  student-pass-holder-lane:
    output: true
  singaporean-familial-ties-lane:
    output: true
  rgl:
    output: true
  rgl-germany:
    output: true
  atp-hong-kong:
    output: true
  connectsg:
    output: true
  atp:
    output: true
  sdf-upgrade:
    output: true
  hong-kong:
    output: true
  


  
##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test
